cursor #cad3f5
cursor_text_color #a5adcb

foreground            #cad3f5
background            #24273a
selection_foreground  #24273a
selection_background  #b7bdf8
url_color             #8aadf4

color0   #1e2030
color1   #ec524a
color2   #6fd66e
color3   #dbd27b
color4   #6585d6
color5   #778cb7
color6   #8aadf4
color7   #abb2bf
color8   #5c6370
color9   #e0605f
color10  #87e086
color11  #e8e097
color12  #b2d4ff
color13  #5782ae
color14  #717cb5
color15  #ffffff
