include custom/everforest-dark.conf
[colors.primary]
background = '#100f0f'
foreground = '#cecdc3'

[colors.selection]
text = '#cecdc3'
background = '#205ea6'

[colors.cursor]
text = '#100f0f'
cursor = '#4385be'

[colors.normal]
black   = '#100F0F'
red     = '#e44a48'
green   = '#72d66e'
yellow  = '#dbd07b'
blue    = '#5384bb'
magenta = '#5e85a8'
cyan    = '#4385BE'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e05f61'
green   = '#89e086'
yellow  = '#e8de97'
blue    = '#96daff'
magenta = '#4a7e97'
cyan    = '#6179a0'
white   = '#ffffff'
