# ----------------------------------------------------- 
# ▄▀█ █▄░█ █ █▀▄▀█ ▄▀█ ▀█▀ █ █▀█ █▄░█
# █▀█ █░▀█ █ █░▀░█ █▀█ ░█░ █ █▄█ █░▀█
#
# name "Dynamic"
# credit https://github.com/mylinuxforwork/dotfiles
# ----------------------------------------------------- 

animations {
    enabled = true
  # a slightly snappy curve (feel free to tweak)
  bezier = ws, 0.05, 0.9, 0.1, 1.05

  # Workspace slide
  animation = workspaces,    1, 6, ws, slide
  animation = workspacesIn,  1, 6, ws, slide
  animation = workspacesOut, 1, 6, ws, slide
}
