-- ╔═══════════════════════════════════════════════════╗
-- ║  WezTerm — nick@cachyos                           ║
-- ║  Styled to match kitty (DankMaterialShell theme)  ║
-- ╚═══════════════════════════════════════════════════╝

local wezterm = require("wezterm")
local act     = wezterm.action
local config  = wezterm.config_builder()

-- ── Color Scheme ─────────────────────────────────────────
-- Switch between "dank-theme" (default) and "matugen" (generated by matugen)
local USE_MATUGEN = false  -- set true after running matugen once

if USE_MATUGEN then
  config.color_scheme_dirs = { wezterm.home_dir .. "/.config/wezterm/colors" }
  config.color_scheme = "matugen"
else
  config.color_scheme_dirs = { wezterm.home_dir .. "/.config/wezterm/colors" }
  config.color_scheme = "dank-theme"
end

-- ── Font ─────────────────────────────────────────────────
config.font = wezterm.font("JetBrainsMono Nerd Font", { weight = "Regular" })
config.font_size = 14.0
config.harfbuzz_features = { "calt=0", "clig=0", "liga=0" }  -- disable ligatures

-- ── Window Appearance ─────────────────────────────────────
config.window_background_opacity = 0.75   -- matches kitty opacity rule
config.window_decorations          = "NONE"
config.window_padding = {
  left   = 30,
  right  = 30,
  top    = 30,
  bottom = 30,
}

-- Background wallpaper with tint (matches kitty background_tint 0.85)
local bg_image = wezterm.home_dir .. "/Pictures/walls/centered/a_cat_with_eyes_wide_open.jpg"
local ok, _ = pcall(wezterm.read_dir, wezterm.home_dir .. "/Pictures/walls/centered")
if ok then
  config.background = {
    {
      source  = { File = bg_image },
      opacity = 1.0,
      hsb     = { brightness = 0.85, saturation = 1.0, hue = 1.0 },
      width   = "100%",
      height  = "100%",
    },
  }
end

-- ── Tab Bar ───────────────────────────────────────────────
config.use_fancy_tab_bar = false
config.tab_bar_at_bottom = false
config.hide_tab_bar_if_only_one_tab = true
config.tab_max_width = 36
config.show_new_tab_button_in_tab_bar = false

-- Powerline slanted tab bar (matches kitty powerline slanted)
local LEFT_ARROW  = utf8.char(0xe0b2)  --
local RIGHT_ARROW = utf8.char(0xe0b0)  --

-- Tab bar colors matching dank-theme
config.colors = {
  tab_bar = {
    background = "#131313",
    active_tab = {
      bg_color  = "#99cbff",
      fg_color  = "#003354",
      intensity = "Bold",
    },
    inactive_tab = {
      bg_color = "#131313",
      fg_color = "#c6c6c6",
    },
    inactive_tab_hover = {
      bg_color = "#1a2535",
      fg_color = "#e2e2e2",
    },
    new_tab = {
      bg_color = "#131313",
      fg_color = "#c6c6c6",
    },
    new_tab_hover = {
      bg_color = "#99cbff",
      fg_color = "#003354",
    },
  },
}

-- Powerline slanted tab titles
wezterm.on("format-tab-title", function(tab, tabs, panes, cfg, hover, max_width)
  local is_active = tab.is_active
  local title = tab.active_pane.title
  if #title > 28 then
    title = title:sub(1, 27) .. "…"
  end
  title = " " .. title .. " [" .. (tab.tab_index + 1) .. "] "

  local active_bg   = "#99cbff"
  local active_fg   = "#003354"
  local inactive_bg = "#131313"
  local inactive_fg = "#c6c6c6"
  local bar_bg      = "#131313"

  if is_active then
    return {
      { Background = { Color = bar_bg } },
      { Foreground = { Color = active_bg } },
      { Text = LEFT_ARROW },
      { Background = { Color = active_bg } },
      { Foreground = { Color = active_fg } },
      { Attribute = { Intensity = "Bold" } },
      { Text = title },
      { Background = { Color = bar_bg } },
      { Foreground = { Color = active_bg } },
      { Text = RIGHT_ARROW },
    }
  else
    return {
      { Background = { Color = bar_bg } },
      { Foreground = { Color = inactive_bg } },
      { Text = LEFT_ARROW },
      { Background = { Color = inactive_bg } },
      { Foreground = { Color = inactive_fg } },
      { Text = title },
      { Background = { Color = bar_bg } },
      { Foreground = { Color = inactive_bg } },
      { Text = RIGHT_ARROW },
    }
  end
end)

-- ── Cursor ────────────────────────────────────────────────
config.default_cursor_style     = "SteadyBlock"
config.cursor_blink_rate        = 0

-- ── Scrollback ────────────────────────────────────────────
config.scrollback_lines         = 10000
config.enable_scroll_bar        = false

-- ── Bell ──────────────────────────────────────────────────
config.audible_bell             = "Disabled"
config.visual_bell              = { fade_in_duration_ms = 0, fade_out_duration_ms = 0 }

-- ── Shell ─────────────────────────────────────────────────
config.default_prog             = { "zsh", "-l" }

-- ── Performance (matches kitty perf settings) ─────────────
config.max_fps                  = 144
config.animation_fps            = 60
config.front_end                = "WebGpu"

-- ── IME / Input ───────────────────────────────────────────
config.use_ime                  = false

-- ── Copy on select ────────────────────────────────────────
config.selection_word_boundary  = " \t\n{}[]()\"'`,;:@│"

-- ── Pane split colors ─────────────────────────────────────
config.inactive_pane_hsb        = { brightness = 0.7, saturation = 0.8, hue = 1.0 }

-- ── Keybinds (matching kitty) ─────────────────────────────
config.disable_default_key_bindings = false
config.keys = {
  -- Reload config
  { key = "r", mods = "CTRL|SHIFT", action = act.ReloadConfiguration },

  -- Clipboard
  { key = "c", mods = "CTRL|SHIFT", action = act.CopyTo("Clipboard") },
  { key = "v", mods = "CTRL|SHIFT", action = act.PasteFrom("Clipboard") },

  -- Font size
  { key = "=",     mods = "CTRL|SHIFT", action = act.IncreaseFontSize },
  { key = "-",     mods = "CTRL|SHIFT", action = act.DecreaseFontSize },
  { key = "0",     mods = "CTRL",       action = act.ResetFontSize },

  -- Tabs
  { key = "t",     mods = "CTRL|SHIFT", action = act.SpawnTab("CurrentPaneDomain") },
  { key = "q",     mods = "CTRL|SHIFT", action = act.CloseCurrentTab({ confirm = false }) },
  { key = "RightArrow", mods = "CTRL|SHIFT", action = act.ActivateTabRelative(1) },
  { key = "LeftArrow",  mods = "CTRL|SHIFT", action = act.ActivateTabRelative(-1) },
  { key = "1", mods = "CTRL|SHIFT", action = act.ActivateTab(0) },
  { key = "2", mods = "CTRL|SHIFT", action = act.ActivateTab(1) },
  { key = "3", mods = "CTRL|SHIFT", action = act.ActivateTab(2) },
  { key = "4", mods = "CTRL|SHIFT", action = act.ActivateTab(3) },
  { key = "5", mods = "CTRL|SHIFT", action = act.ActivateTab(4) },
  { key = "6", mods = "CTRL|SHIFT", action = act.ActivateTab(5) },
  { key = "7", mods = "CTRL|SHIFT", action = act.ActivateTab(6) },
  { key = "8", mods = "CTRL|SHIFT", action = act.ActivateTab(7) },
  { key = "9", mods = "CTRL|SHIFT", action = act.ActivateTab(8) },

  -- Pane splits (kitty: s=hsplit, a=vsplit)
  { key = "s",     mods = "CTRL|SHIFT", action = act.SplitHorizontal({ domain = "CurrentPaneDomain" }) },
  { key = "a",     mods = "CTRL|SHIFT", action = act.SplitVertical({ domain = "CurrentPaneDomain" }) },

  -- Pane nav
  { key = "Enter", mods = "CTRL|SHIFT", action = act.SpawnWindow },
  { key = "w",     mods = "CTRL|SHIFT", action = act.CloseCurrentPane({ confirm = false }) },

  -- Search (kitty: ctrl+shift+f)
  { key = "f",     mods = "CTRL|SHIFT", action = act.Search({ CaseSensitiveString = "" }) },
}

-- ── Mouse ─────────────────────────────────────────────────
config.mouse_bindings = {
  -- Copy on select (like kitty copy_on_select)
  {
    event  = { Up = { streak = 1, button = "Left" } },
    mods   = "NONE",
    action = act.CompleteSelectionOrOpenLinkAtMouseCursor("ClipboardAndPrimarySelection"),
  },
}

return config
