[General]
Always_Use_The_Terminal=true
Aur_No_Confirm_Param=true
Aur_PackageList_Ordered_Col=1
Aur_PackageList_Sort_Order=0
Aur_Tool_Name=yay
Backend=alpm
Cache_Cleaner_Window_Size=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\x5\xf4\0\0\x5)\0\0\0\0\0\0\0\0\0\0\x5\xf4\0\0\x5)\0\0\0\x1\x2\0\0\0\n\0\0\0\0\0\0\0\0\0\0\0\x5\xf4\0\0\x5))
Current_Tab_Index=3
Distro_RSS_Url=https://archlinux.org/feeds/news/
Enable_Transaction_Dialog_In_System_Upgrade=false
Instant_Search=false
Internet_Checking_Domain=www.google.com
Keep_Num_Installed=0
Keep_Num_Uninstalled=0
LastCheckUpdatesTime=@DateTime(\0\0\0\x10\0\0\0\0\0\0%\x8d\xad\x3#\xfc\xae\0)
OptionalDeps_Window_Size=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\x2/\0\0\x1\x91\0\0\0\0\0\0\0\0\0\0\x2/\0\0\x1\x91\0\0\0\x1\x2\0\0\0\n\0\0\0\0\0\0\0\0\0\0\0\x2/\0\0\x1\x91)
PackageList_Ordered_Col=0
PackageList_Sort_Order=0
Package_Download_Size_Column_Width=650
Package_Icon_Column_Width=44
Package_Install_Date_Column_Width=140
Package_Install_Reason_Column_Width=376
Package_Name_Column_Width=400
Package_Repository_Column_Width=150
Package_Version_Column_Width=260
Play_Bell_Sound_On_Terminal_Password_Input=true
Repo_Editor_Window_Size=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x3\x34\0\0\x1\xd5\0\0\t%\0\0\x6\xfe\0\0\x3\x34\0\0\x1\xd5\0\0\t%\0\0\x6\xfe\0\0\0\x1\x2\0\0\0\n\0\0\0\x3\x34\0\0\x1\xd5\0\0\t%\0\0\x6\xfe)
Search_Method=0
Search_Outdated_Aur_Packages=true
Show_Groups_Panel=false
Show_Package_Install_Date_Column=true
Show_Package_Install_Reason_Column=true
Splitter_Horizontal_State=@ByteArray(\0\0\0\xff\0\0\0\x1\0\0\0\x2\0\0\0\xc0\0\0\0\xf9\x1\xff\xff\xff\xff\x1\0\0\0\x2\0)
Terminal_Color_Scheme=Linux
Terminal_Font_Family=SF Mono
Terminal_Font_Point_Size=13
Transaction_Window_Size=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\x82\0\0\0z\0\0\x2k\0\0\x1\xe3\0\0\0\x82\0\0\0z\0\0\x2k\0\0\x1\xe3\0\0\0\x1\x2\0\0\0\n\0\0\0\0\x82\0\0\0z\0\0\x2k\0\0\x1\xe3)
Use_Alternate_Row_Color=true
Use_Default_App_Icon=true
Window_Size=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\n\0\0\0\0H\0\0\xf\xba\0\0\x4\x38\0\0\n\0\0\0\0H\0\0\r\xb3\0\0\x4\x38\0\0\0\0\x2\0\0\0\a\x80\0\0\n\0\0\0\0H\0\0\xf\xba\0\0\x4\x38)
