# -- Autostart -- #

# Waybar
#exec-once = bash /home/nick/.config/waybar/scripts/launch.sh

# Wallpaper
#exec-once = swww-daemon
exec-once = dbus-update-activation-environment --systemd --all
exec-once = systemctl --user start hyprland-session.target

# Privilege escalation
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = pypr &

# Auto-mount removable storage
exec-once = udiskie
exec-once = hypridle &
#exec-once = nm-applet &
# Idling
#exec-once = mpvpaper --fork -o "no-audio loop hwdec=auto" "*" /home/nick/Pictures/walls/animated/ganyu.mp4



#exec-once = hypridle &
exec-once = hyprpm reload
#exec-once = hyprctl setcursor capitiane-cursor-white
# Notification center
#exec-once = swaync
#exec-once = waypaper --restore
# Cursor
exec-once = hyprctl setcursor bloom 24

