# -- Autostart -- #

# Waybar
exec-once = bash /home/nick/.config/waybar/scripts/launch.sh

# Wallpaper
exec-once = swww-daemon
exec-once = dbus-update-activation-environment --systemd --all
exec-once = systemctl --user start hyprland-session.target
# Privilege escalation
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = pypr &
#exec-once = udiskie
exec-once = hypridle &
exec-once = nm-applet &
exec-once = hyprpm reload

# Auto-mount removable storage
# Idling
#exec-once = mpvpaper --fork -o "no-audio loop" "DP-3" /home/nick/Pictures/walls/animated/city.gif


#exec-once = hypridle &
#exec-once = hyprctl setcursor capitiane-cursor-white
# Notification center
#exec-once = snixembed 
#exec-once = swaync
#exec-once = waypaper --restore
# Cursor
#

