# -- Workspaces -- #

# --- Persistent Workspaces ---
# --- Persistent Icon Workspaces (Locked to Monitors) ---

# Main monitor (DP-3)
workspace = 1, monitor:DP-3, name:, persistent:true
workspace = 2, monitor:DP-3, name:, persistent:true
workspace = 3, monitor:DP-3, name:󰆍, persistent:true

# Portrait monitor (DP-2)
workspace = 4, monitor:DP-2, name:󰖟, persistent:true
workspace = 5, monitor:DP-2, name:󰎈, persistent:true
workspace = 6, monitor:DP-2, name:, persistent:true


# Set special workspace icons with Nerd Fonts
# workspace binding
#workspace=1, monitor:DP-3
#workspace=2, monitor:DP-2
#workspace=3, monitor:DP-3
#workspace=4, monitor:DP-2
#workspace=6, monitor:DP-3
#workspace=8, monitor:DP-3
#workspace=9, monitor:DP-3
