
$background_i = rgb(17130b)

$error_i = rgb(ffb4ab)

$error_container_i = rgb(93000a)

$inverse_on_surface_i = rgb(343027)

$inverse_primary_i = rgb(765a0b)

$inverse_surface_i = rgb(eae1d4)

$on_background_i = rgb(eae1d4)

$on_error_i = rgb(690005)

$on_error_container_i = rgb(ffdad6)

$on_primary_i = rgb(3e2e00)

$on_primary_container_i = rgb(ffdf98)

$on_primary_fixed_i = rgb(251a00)

$on_primary_fixed_variant_i = rgb(5a4300)

$on_secondary_i = rgb(3a2f15)

$on_secondary_container_i = rgb(f4e0bb)

$on_secondary_fixed_i = rgb(241a04)

$on_secondary_fixed_variant_i = rgb(52452a)

$on_surface_i = rgb(eae1d4)

$on_surface_variant_i = rgb(d0c5b4)

$on_tertiary_i = rgb(1b361d)

$on_tertiary_container_i = rgb(caebc6)

$on_tertiary_fixed_i = rgb(06210a)

$on_tertiary_fixed_variant_i = rgb(324d32)

$outline_i = rgb(999080)

$outline_variant_i = rgb(4d4639)

$primary_i = rgb(e7c26c)

$primary_container_i = rgb(5a4300)

$primary_fixed_i = rgb(ffdf98)

$primary_fixed_dim_i = rgb(e7c26c)

$scrim_i = rgb(000000)

$secondary_i = rgb(d7c5a0)

$secondary_container_i = rgb(52452a)

$secondary_fixed_i = rgb(f4e0bb)

$secondary_fixed_dim_i = rgb(d7c5a0)

$shadow_i = rgb(000000)

$source_color_i = rgb(cabda5)

$surface_i = rgb(17130b)

$surface_bright_i = rgb(3d392f)

$surface_container_i = rgb(231f17)

$surface_container_high_i = rgb(2e2921)

$surface_container_highest_i = rgb(39342b)

$surface_container_low_i = rgb(1f1b13)

$surface_container_lowest_i = rgb(110e07)

$surface_dim_i = rgb(17130b)

$surface_tint_i = rgb(e7c26c)

$surface_variant_i = rgb(4d4639)

$tertiary_i = rgb(afcfab)

$tertiary_container_i = rgb(324d32)

$tertiary_fixed_i = rgb(caebc6)

$tertiary_fixed_dim_i = rgb(afcfab)
