$image = /home/nick/Pictures/walls/digital/a_city_in_the_rain.jpeg

$background = rgb(rgb(16, 20, 24))

$error = rgb(rgb(255, 180, 171))

$error_container = rgb(rgb(147, 0, 10))

$inverse_on_surface = rgb(rgb(45, 49, 53))

$inverse_primary = rgb(rgb(49, 98, 141))

$inverse_surface = rgb(rgb(224, 226, 232))

$on_background = rgb(rgb(224, 226, 232))

$on_error = rgb(rgb(105, 0, 5))

$on_error_container = rgb(rgb(255, 218, 214))

$on_primary = rgb(rgb(0, 51, 85))

$on_primary_container = rgb(rgb(207, 229, 255))

$on_primary_fixed = rgb(rgb(0, 29, 52))

$on_primary_fixed_variant = rgb(rgb(18, 74, 115))

$on_secondary = rgb(rgb(36, 50, 64))

$on_secondary_container = rgb(rgb(213, 228, 247))

$on_secondary_fixed = rgb(rgb(14, 29, 42))

$on_secondary_fixed_variant = rgb(rgb(58, 72, 87))

$on_surface = rgb(rgb(224, 226, 232))

$on_surface_variant = rgb(rgb(194, 199, 207))

$on_tertiary = rgb(rgb(57, 42, 73))

$on_tertiary_container = rgb(rgb(240, 219, 255))

$on_tertiary_fixed = rgb(rgb(35, 21, 50))

$on_tertiary_fixed_variant = rgb(rgb(80, 64, 96))

$outline = rgb(rgb(140, 145, 153))

$outline_variant = rgb(rgb(66, 71, 78))

$primary = rgb(rgb(157, 203, 251))

$primary_container = rgb(rgb(18, 74, 115))

$primary_fixed = rgb(rgb(207, 229, 255))

$primary_fixed_dim = rgb(rgb(157, 203, 251))

$scrim = rgb(rgb(0, 0, 0))

$secondary = rgb(rgb(185, 200, 218))

$secondary_container = rgb(rgb(58, 72, 87))

$secondary_fixed = rgb(rgb(213, 228, 247))

$secondary_fixed_dim = rgb(rgb(185, 200, 218))

$shadow = rgb(rgb(0, 0, 0))

$source_color = rgb(rgb(12, 22, 32))

$surface = rgb(rgb(16, 20, 24))

$surface_bright = rgb(rgb(54, 57, 62))

$surface_container = rgb(rgb(29, 32, 36))

$surface_container_high = rgb(rgb(39, 42, 47))

$surface_container_highest = rgb(rgb(50, 53, 58))

$surface_container_low = rgb(rgb(24, 28, 32))

$surface_container_lowest = rgb(rgb(11, 14, 18))

$surface_dim = rgb(rgb(16, 20, 24))

$surface_tint = rgb(rgb(157, 203, 251))

$surface_variant = rgb(rgb(66, 71, 78))

$tertiary = rgb(rgb(212, 190, 230))

$tertiary_container = rgb(rgb(80, 64, 96))

$tertiary_fixed = rgb(rgb(240, 219, 255))

$tertiary_fixed_dim = rgb(rgb(212, 190, 230))

