$image = Null

$background = rgb(rgb(14, 20, 22))

$error = rgb(rgb(255, 180, 171))

$error_container = rgb(rgb(147, 0, 10))

$inverse_on_surface = rgb(rgb(43, 49, 51))

$inverse_primary = rgb(rgb(0, 104, 119))

$inverse_surface = rgb(rgb(222, 227, 229))

$on_background = rgb(rgb(222, 227, 229))

$on_error = rgb(rgb(105, 0, 5))

$on_error_container = rgb(rgb(255, 218, 214))

$on_primary = rgb(rgb(0, 54, 63))

$on_primary_container = rgb(rgb(163, 238, 255))

$on_primary_fixed = rgb(rgb(0, 31, 37))

$on_primary_fixed_variant = rgb(rgb(0, 78, 90))

$on_secondary = rgb(rgb(28, 52, 57))

$on_secondary_container = rgb(rgb(205, 231, 237))

$on_secondary_fixed = rgb(rgb(5, 31, 36))

$on_secondary_fixed_variant = rgb(rgb(51, 74, 80))

$on_surface = rgb(rgb(222, 227, 229))

$on_surface_variant = rgb(rgb(191, 200, 203))

$on_tertiary = rgb(rgb(38, 47, 77))

$on_tertiary_container = rgb(rgb(220, 225, 255))

$on_tertiary_fixed = rgb(rgb(17, 26, 55))

$on_tertiary_fixed_variant = rgb(rgb(61, 70, 101))

$outline = rgb(rgb(137, 146, 149))

$outline_variant = rgb(rgb(63, 72, 75))

$primary = rgb(rgb(131, 210, 228))

$primary_container = rgb(rgb(0, 78, 90))

$primary_fixed = rgb(rgb(163, 238, 255))

$primary_fixed_dim = rgb(rgb(131, 210, 228))

$scrim = rgb(rgb(0, 0, 0))

$secondary = rgb(rgb(178, 203, 209))

$secondary_container = rgb(rgb(51, 74, 80))

$secondary_fixed = rgb(rgb(205, 231, 237))

$secondary_fixed_dim = rgb(rgb(178, 203, 209))

$shadow = rgb(rgb(0, 0, 0))

$source_color = rgb(rgb(63, 110, 120))

$surface = rgb(rgb(14, 20, 22))

$surface_bright = rgb(rgb(52, 58, 60))

$surface_container = rgb(rgb(27, 33, 34))

$surface_container_high = rgb(rgb(37, 43, 44))

$surface_container_highest = rgb(rgb(48, 54, 55))

$surface_container_low = rgb(rgb(23, 29, 30))

$surface_container_lowest = rgb(rgb(9, 15, 16))

$surface_dim = rgb(rgb(14, 20, 22))

$surface_tint = rgb(rgb(131, 210, 228))

$surface_variant = rgb(rgb(63, 72, 75))

$tertiary = rgb(rgb(188, 197, 235))

$tertiary_container = rgb(rgb(61, 70, 101))

$tertiary_fixed = rgb(rgb(220, 225, 255))

$tertiary_fixed_dim = rgb(rgb(188, 197, 235))

