[colors]
background = '#1c1c1c'
foreground = '#fbf1c7'

cursor_bg = '#83a598'
cursor_fg = '#1c1c1c'
cursor_border = '#83a598'

selection_bg = '#458588'
selection_fg = '#fbf1c7'

ansi = ['#1c1c1c', '#bd7655', '#52a556', '#cec45c', '#759c8d', '#2f4c41', '#83a598', '#a2ada9']
brights = ['#767e7b', '#dea58b', '#80c683', '#f7efa0', '#95b5a9', '#b7d6ca', '#d1e7de', '#e9efec']
