[colors.primary]
background = '#131313'
foreground = '#e2e2e2'

[colors.selection]
text = '#e2e2e2'
background = '#00468c'

[colors.cursor]
text = '#131313'
cursor = '#a9c7ff'

[colors.normal]
black   = '#131313'
red     = '#ff729a'
green   = '#7fff92'
yellow  = '#fff872'
blue    = '#90b2f2'
magenta = '#2d4676'
cyan    = '#a9c7ff'
white   = '#eff4ff'

[colors.bright]
black   = '#999da5'
red     = '#ff9fba'
green   = '#a5ffb2'
yellow  = '#fffaa5'
blue    = '#b5cfff'
magenta = '#c2d7ff'
cyan    = '#d8e5ff'
white   = '#f8faff'
