plugin {
  hyprbars {
    bar_height = 33
    bar_color  = $mg_bar
    bar_blur   = true
    bar_title_enabled = true
    bar_text_size     = 12
    bar_text_font     = "SF Pro Display Semibold"
    bar_text_align        = left
    bar_buttons_alignment = right
    bar_padding        = 15
    bar_button_padding = 6

    col.text = $mg_text
    # main colors (use rgba/rgb directly to avoid var parsing weirdness)
      col.text_inactive = $mg_text_alpha
      col.bg = $mg_bar
      col.bg_inactive = $mg_bar_alpha

    # optional: active/inactive split (if your hyprbars build has it)
    # bar_color_inactive = rgba(1d2024aa)

    
   
 

    # buttons (hyprbars-button lines are supported)
    hyprbars-button = rgb(ffb4ab), 18, , hyprctl dispatch killactive
    hyprbars-button = rgb(dbbce1), 18, 󰊓, hyprctl dispatch fullscreen 1
    hyprbars-button = rgb(a7c8ff), 18, 󰖯, hyprctl dispatch togglefloating
    

    # Spacer (invisible)
    hyprbars-button = rgba(00000000), 28, , sh -c ':'

    # Double click on bar
    on_double_click = hyprctl dispatch fullscreen 1
  }